version: '3.5'
services:
  db: # Banco de dados
    image: mongo:6.0.9-jammy
    ports:
      - "27017:27017/tcp"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passRoot
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1GB'
  api1:
    build:
      context: ./
    environment:
      PORT: 3001
      DB_USER: rinhaRoot
      DB_PASS: rinhaRootSecret
      DB_SRVR: db
      DB_NAME: RINHA_DB
      DB_PORT: 27017
    ports:
      - "3001:3001"
    depends_on:
      - db
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.5GB'
  api2:
    build:
      context: ./
    environment:
      PORT: 3002
      DB_USER: rinhaRoot
      DB_PASS: rinhaRootSecret
      DB_SRVR: db
      DB_NAME: RINHA_DB
      DB_PORT: 27017
    restart: always
    ports:
      - "3002:3002"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.37'
          memory: '0.25GB'
  nginx: # Load Balancer
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./rinha-nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
    ports:
      - "9999:9999"
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "0.5GB"

